spring:
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}

env:
  server-base-url: ${DEV_SERVER_BASE_URL}
  client-base-url: ${DEV_CLIENT_BASE_URL}

server:
  port: 8081