spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        query.in_clause_parameter_padding: true


env:
  server-base-url: ${DEV_SERVER_BASE_URL}
  client-base-url: ${DEV_CLIENT_BASE_URL}

server:
  port: 8081