spring:
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}

env:
  server-base-url: ${LOCAL_SERVER_BASE_URL}
  client-base-url: ${LOCAL_CLIENT_BASE_URL}

server:
  port: 8080